spring:
  datasource:
    url: jdbc:postgresql://mafdbpgsrv.postgres.database.azure.com:5432/postgres
    username: mohamed
    password: Azure2022
    #url: jdbc:postgresql://localhost:5432/postgres#url
    #username: postgres
    #password: mohamed
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
